### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by zhangp365** [jojkaart/ComfyUI-sampler-lcm-alternative#1]
I read the README carefully and found the nodes. But after that, I don't know how to connect that. Could you please put the example workflows in the README, thank you! 
![image](https://github.com/jojkaart/ComfyUI-sampler-lcm-alternative/assets/144313702/666e3b95-b508-46db-9e47-fa585d07e78b)

**Comment by jojkaart** [comment]
I added an image with an example workflow. You can just drag&drop it into comfyui to get that exact workflow.

**Comment by jojkaart** [comment]
oh right, closing this ticket.

**Comment by jojkaart** [comment]
... I guess I clicked the wrong button

**Comment by zhangp365** [comment]
ok, I can use these nodes now. Thank you!
