### ISSUE TITLE
Less denoise?

### ISSUE THREAD

**Issue by Simn** [jojkaart/ComfyUI-sampler-lcm-alternative#2]
Is there a way to run this kind of setup with less than 1.0 denoise? I'm not sure how this is supposed to work with SamplerCustom in general, it seems that there should be some more options to the LCMScheduler node.

**Comment by jojkaart** [comment]
You can use the core node called splitsigmas node to do partial denoising.

**Comment by Simn** [comment]
Ah so that's what that's for! Thanks for the pointer, I'll go see if I can figure it out.
