### ISSUE TITLE
Really need denoising parameter

### ISSUE THREAD

**Issue by Anshi701** [jojkaart/ComfyUI-sampler-lcm-alternative#4]
Your cycle node is giving good results, but it can not do any img2img workflows. I know about splitsigmas node, but it not the same as denoising, because first steps omitted for scheduler too and it changes behavior of generation.
It will be best to have denoising parameter alongside other ones!
And thank you for your work - it is very impressive!

**Comment by cyandddd** [comment]
really need this! i think is just a few lines in the code. please help us get the denoising parameter. this would be perfect then. I see the creator of customsampler posted a way to add denoising parameter but the same code does not work here. 

https://github.com/comfyanonymous/ComfyUI/commit/e82942cc293a7f707f3ba5611e33ec2284278268

**Comment by jojkaart** [comment]
You could've just used BasicScheduler with the `sgm_uniform` scheduler instead, but I've now added denoise parameter to LCMScheduler.
